import type { APIRequestContext } from '@playwright/test';
import { STAGING_CREDENTIALS } from '../util/api-token';

/**
 * RC 3.15 #3808 — the billing validation gains "Entlassmanagement-Timing", which fails a GKV
 * discharge VO whose carried-out sessions lie outside the 7/12-day window.
 *
 * Shipped as `a0b961b4cbb` (PR #3861). The ticket is unusually testable, because every surface
 * it touches is readable:
 *
 *  - **The registry.** `GET /validations` serves the new row, so its existence, timing, severity,
 *    category, insurance types and VO kinds are all facts rather than inferences — the #3708
 *    technique. It is the deployment probe too: a `timing: billing` discharge row could not exist
 *    before.
 *  - **The verdict.** `GET /prescription_validations?prescription=` carries `passed` AND
 *    **`autoNote`** — the note AC4 specifies, generated by the API, so it is NOT in the frontend
 *    bundle and can only be read here.
 *  - **The writes**, for AC5: `PATCH /prescription_validations/{id}` is the manual Pass and
 *    `POST /prescriptions/{id}/check-billing-validation` is Re-check. Both are bounded and the
 *    pair is self-restoring, because the re-check recomputes the automatic verdict.
 */

export const API_BASE = 'https://api.staging.therapios.de';

/** The new check's own row. A NEW description shipped rather than reusing the creation row's. */
export const BILLING_CHECK = 'billing_discharge_management_timing';
export const CREATION_CHECK = 'discharge_management_timing';

/** AC2: day 7 and day 12 counted from the issue date, both inclusive. */
export const START_BY_DAYS = 7;
export const END_DAYS = 12;

export type Validation = {
  id: number;
  description: string;
  timing: string;
  severity: string;
  category: string;
  insuranceTypes: string[];
  voKinds: string[];
};

export type Session = { date: string; counts: boolean; planned: boolean; rejected: boolean; signed: boolean };

export type Vo = {
  id: number;
  number: string;
  issueDate: string;
  insuranceType: string | null;
  isDischargeManagement: boolean;
  dischargeDate: string | null;
  treatmentStatus: string;
};

export type Verdict = { id: number; validationId: number; passed: boolean; autoNote: string | null };

/** ───────────────── the rule and its note, ported ───────────────── */

export function addDays(iso: string, n: number): string {
  return new Date(Date.parse(`${iso.slice(0, 10)}T00:00:00Z`) + n * 86_400_000).toISOString().slice(0, 10);
}

/** DD.MM.YYYY, the format the note uses. */
export function de(iso: string): string {
  const [y, m, d] = iso.slice(0, 10).split('-');
  return `${d}.${m}.${y}`;
}

/**
 * AC2's table: which carried-out sessions lie outside the window.
 *
 * First session on or before day 7 → everything after day 12 is outside.
 * First session after day 7        → EVERY session is outside (the VO never became valid).
 * No counting session              → nothing is outside; the check passes.
 */
export function outsideWindow(issueDate: string, sessions: Session[]): string[] {
  const counting = sessions.filter((s) => s.counts).map((s) => s.date).sort();
  if (counting.length === 0) return [];
  const startBy = addDays(issueDate, START_BY_DAYS);
  const end = addDays(issueDate, END_DAYS);
  return counting[0] > startBy ? counting : counting.filter((d) => d > end);
}

/**
 * The note AC4 specifies, rebuilt independently.
 *
 * Compared against the served `autoNote` rather than merely checking that a note exists, so a
 * check that flags the right VOs but names the wrong dates still fails (#3576's technique).
 */
export function expectedNote(issueDate: string, sessions: Session[]): string | null {
  const outside = outsideWindow(issueDate, sessions);
  if (outside.length === 0) return null;
  return (
    `Entlassmanagement: Behandlungen außerhalb des Zeitraums ` +
    `(Ausstellung: ${de(issueDate)}, Beginn bis: ${de(addDays(issueDate, START_BY_DAYS))}, ` +
    `Ende: ${de(addDays(issueDate, END_DAYS))}): ${outside.map(de).join(', ')}.`
  );
}

/** AC1: the check runs for GKV only. */
export function checkApplies(vo: { insuranceType: string | null }): boolean {
  return vo.insuranceType === 'public';
}

/** AC1 + AC2 together: the verdict the engine should store, or null when the check does not run. */
export function expectedPassed(vo: Vo, sessions: Session[]): boolean | null {
  if (!checkApplies(vo)) return null;
  if (!vo.isDischargeManagement) return true;
  return outsideWindow(vo.issueDate, sessions).length === 0;
}

export class DischargeBillingCheckPage {
  private token: string | null = null;

  constructor(private request: APIRequestContext) {}

  private async bearer(): Promise<string> {
    if (this.token) return this.token;
    for (let attempt = 0; attempt < 5; attempt++) {
      try {
        const res = await this.request.post(`${API_BASE}/auth`, {
          headers: { 'Content-Type': 'application/json' },
          data: {
            username: STAGING_CREDENTIALS.superadmin.email,
            password: STAGING_CREDENTIALS.superadmin.password,
          },
          timeout: 60_000,
        });
        if (res.ok()) {
          this.token = (await res.json()).token as string;
          return this.token;
        }
      } catch {
        /* a connect timeout throws before any status exists (#3872) */
      }
      await new Promise((r) => setTimeout(r, 4000 * (attempt + 1)));
    }
    throw new Error('POST /auth failed after retries');
  }

  private async get<T = any>(path: string): Promise<T> {
    let last = '';
    for (let attempt = 0; attempt < 4; attempt++) {
      try {
        const res = await this.request.get(`${API_BASE}${path}`, {
          headers: { Authorization: `Bearer ${await this.bearer()}`, Accept: 'application/ld+json' },
          timeout: 180_000,
        });
        if (res.ok()) return (await res.json()) as T;
        last = `status ${res.status()}`;
        if (res.status() < 500) break;
      } catch (e) {
        last = String(e).slice(0, 120);
      }
      await new Promise((r) => setTimeout(r, 3000 * (attempt + 1)));
    }
    throw new Error(`GET ${path} failed: ${last}`);
  }

  /** Every registered check. `itemsPerPage` must be raised or most of the 52 are hidden (#3708). */
  async validations(): Promise<Validation[]> {
    const b = await this.get<{ member: any[] }>('/validations?itemsPerPage=200');
    return (b.member ?? []).map((v) => ({
      id: Number(v.id),
      description: String(v.description ?? ''),
      timing: String(v.timing ?? ''),
      severity: String(v.severity ?? ''),
      category: String(v.category ?? ''),
      insuranceTypes: v.applicableInsuranceTypes ?? [],
      voKinds: v.applicableVoKinds ?? [],
    }));
  }

  /** VOs by their printed number, batched. */
  async vosByNumber(numbers: string[]): Promise<Vo[]> {
    const q = numbers.map((n) => `prescriptionId[]=${encodeURIComponent(n)}`).join('&');
    const b = await this.get<{ member: any[] }>(`/prescriptions?${q}&itemsPerPage=200`);
    return (b.member ?? []).map((v) => ({
      id: Number(v.id),
      number: String(v.prescriptionId ?? ''),
      issueDate: String(v.date ?? '').slice(0, 10),
      insuranceType: v.insuranceType ?? null,
      isDischargeManagement: Boolean(v.isDischargeManagement),
      dischargeDate: v.dischargeDate ? String(v.dischargeDate).slice(0, 10) : null,
      treatmentStatus: String(v.treatmentStatus ?? ''),
    }));
  }

  /**
   * Sessions per VO.
   *
   * The counting rule is #3775's and the fields are `rejectedTreatment` /
   * `rejectedTreatmentWithSignature` — the short `rejected` / `rejectedWithSignature` do not exist
   * on an Activity, so a predicate on them excludes nothing (#3649, #3814). A refusal WITH the
   * patient's signature counts; one without does not; a planned session never does.
   */
  async sessionsByVo(ids: number[]): Promise<Map<number, Session[]>> {
    const out = new Map<number, Session[]>();
    for (const id of ids) out.set(id, []);
    for (let i = 0; i < ids.length; i += 60) {
      const q = ids.slice(i, i + 60).map((n) => `prescription[]=${n}`).join('&');
      const b = await this.get<{ member: any[] }>(`/activities?${q}&itemsPerPage=4000`);
      for (const a of b.member ?? []) {
        const pid = DischargeBillingCheckPage.idOf(a.prescription);
        if (pid === null || !a.date) continue;
        const planned = String(a.treatmentType ?? '') === 'planned';
        const rejected = a.rejectedTreatment === true;
        const signed = a.rejectedTreatmentWithSignature === true;
        out.get(pid)?.push({
          date: String(a.date).slice(0, 10),
          planned,
          rejected,
          signed,
          counts: !planned && !(rejected && !signed),
        });
      }
    }
    for (const [, v] of out) v.sort((a, b) => a.date.localeCompare(b.date));
    return out;
  }

  /**
   * A VO's stored verdicts.
   *
   * TRAP: the registered filter is the bare **`prescription=`**. `prescription.id=` is accepted
   * and SILENTLY IGNORED — it returns an unfiltered page, so every VO appears to carry a hundred
   * verdicts belonging to other VOs. `autoNote` is OMITTED when null, so a passing row simply has
   * no such key.
   */
  async verdicts(voId: number): Promise<Verdict[]> {
    const b = await this.get<{ member: any[] }>(
      `/prescription_validations?prescription=${voId}&itemsPerPage=200`,
    );
    return (b.member ?? []).map((r) => ({
      id: Number(r.id),
      validationId: DischargeBillingCheckPage.idOf(r.validation) ?? -1,
      passed: Boolean(r.passed),
      autoNote: r.autoNote ?? null,
    }));
  }

  /** Proof that `prescription=` narrows and `prescription.id=` does not. */
  async verdictFilterTotals(voId: number): Promise<{ scoped: number; ignored: number }> {
    const a = await this.get<{ member: any[] }>(`/prescription_validations?prescription=${voId}&itemsPerPage=200`);
    const b = await this.get<{ member: any[] }>(`/prescription_validations?prescription.id=${voId}&itemsPerPage=200`);
    return { scoped: (a.member ?? []).length, ignored: (b.member ?? []).length };
  }

  // ───────────────────────── the writes, for AC5 only ─────────────────────────

  /** The manual "Pass" on a failed check. */
  async setPassed(verdictId: number, passed: boolean): Promise<number> {
    const res = await this.request.fetch(`${API_BASE}/prescription_validations/${verdictId}`, {
      method: 'PATCH',
      headers: {
        Authorization: `Bearer ${await this.bearer()}`,
        'Content-Type': 'application/merge-patch+json',
      },
      data: { passed },
      timeout: 120_000,
    });
    return res.status();
  }

  /** The "Erneut prüfen" button. Recomputes every billing check for the VO. */
  async recheck(voId: number): Promise<{ status: number; checked: number }> {
    const res = await this.request.fetch(`${API_BASE}/prescriptions/${voId}/check-billing-validation`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${await this.bearer()}`, 'Content-Type': 'application/json' },
      data: {},
      timeout: 180_000,
    });
    let checked = -1;
    try {
      checked = Number((await res.json()).checked ?? -1);
    } catch {
      /* non-JSON */
    }
    return { status: res.status(), checked };
  }

  /** The Entlassmanagement marker on the VO form. Used self-restoring for AC5's third row. */
  async setDischargeMarker(voId: number, value: boolean): Promise<number> {
    const res = await this.request.fetch(`${API_BASE}/prescriptions/${voId}`, {
      method: 'PATCH',
      headers: {
        Authorization: `Bearer ${await this.bearer()}`,
        'Content-Type': 'application/merge-patch+json',
      },
      data: { isDischargeManagement: value },
      timeout: 120_000,
    });
    return res.status();
  }

  async marker(voId: number): Promise<boolean> {
    return Boolean((await this.get<any>(`/prescriptions/${voId}`)).isDischargeManagement);
  }

  static idOf(iri: unknown): number | null {
    if (typeof iri === 'string') {
      const n = Number(iri.split('/').pop());
      return Number.isFinite(n) ? n : null;
    }
    if (iri && typeof iri === 'object' && 'id' in (iri as any)) return Number((iri as any).id);
    return null;
  }
}
