import { test, expect } from '@playwright/test';
import {
  NoticeWordingPage,
  FIXTURES,
  WORDING,
  SUPERSEDED,
  type LetterRead,
} from '../../../Pages/admin/admin.notice-wording.page';
import { API_BASE } from '../../../Pages/util/api-token';

/**
 * RC 3.14 — the Vorabinformation's exemption block gets three corrected sentences (#3668,
 * commit `9fd6fa547`).
 *
 * The operations team sent corrected wording: two existing sentences reworded and one new sentence
 * saying Therapios always needs a copy of the exemption card, even when the patient's residential
 * facility already has one on file. The same three land in the Blanko variant (#3228's Ergotherapie
 * and Physiotherapie letters) so the two letters stay consistent.
 *
 * **Deployed; all six ACs verified on freshly generated letters. 7 passed, 0 `fixme`.**
 *
 * ## A rendering ticket has one authoritative surface, and it is not the archive
 *
 * A notice is archived at generation and **never re-rendered** — the ticket says so itself
 * ("existing letters already in the Document Center keep their current wording"). So the archive
 * can date the change but never confirm it, and every assertion here runs against a letter
 * generated by the test. That also settles deployment, which `GET /status` cannot: these are Twig
 * templates and `/status` reports the RELEASE, not the commit (#3704).
 *
 * ## THE TRAP THAT DELETES THE SENTENCE UNDER TEST
 *
 * **`pdfText()` drops AC1's line.** On this letter it renders the callout as *"…die Rechnung
 * erhalten Sie erst nach Sie haben eine Zuzahlungsbefreiung?"* — the phrase AC1 is about is simply
 * gone, and a test written on it fails while the letter is correct. `pdfDocText()` (positioned
 * runs, `pdf-layout.ts`) recovers it. The same extractor gap #3559's reminder letter hit; a test
 * pins it here so the next person does not re-diagnose it as a rendering defect.
 *
 * ## The AC's prose is not the shipped string, twice over
 *
 *  - **AC1 quotes a comma; the letter has an EN DASH.** "Bitte überweisen Sie noch kein Geld**,** die
 *    Rechnung…" vs the template's `&ndash;`, which this ticket never touched — it changed only the
 *    ending phrase. Asserting the AC's literal sentence fails on a correct implementation (#3666's
 *    `÷`-vs-`/` again), so every sentence is matched on its PARTS, in order.
 *  - **The email is entity-driven.** `brand_email` renders `info@curano.de` for a Curano entity and
 *    `info@therapios.de` for a Therapios one — both appear across these three fixtures. The ACs
 *    quote the Therapios address literally, so it is matched as a pattern.
 *
 * ## FINDING: the standard letter now contradicts itself about the same phrase
 *
 * AC1 updates the callout to "nach **Ende Ihrer Behandlung**", and AC4 updates the Blanko letter's
 * final-invoice sentence to the same. The standard letter carries **its own copy of AC4's
 * sentence**, a few lines below the callout — *"Sie erhalten die finale Rechnung nach
 * **Behandlungsende**, berechnet werden dabei nur tatsächlich durchgeführte Behandlungen."* — and it
 * was not updated. So one letter now says it both ways, ~500 characters apart, while the Blanko
 * letter says it only the new way. Strictly out of scope ("does NOT change: any other paragraph"),
 * but it is the ops team's own corrected phrase left behind in the very letter they corrected, so
 * it is reported as a green `FINDING` test rather than a failure.
 *
 * ## The #3522 interaction, which the commit had to solve
 *
 * The new sentence runs to a further line on all three variants, and the commit's own note says
 * **both the regular letter and the Ergotherapie Blanko went to two pages** until the paragraph
 * gaps were tightened from 5px to 3px. That puts this ticket in direct tension with #3522 ("a
 * Vorabinformation with ≤3 prescribed treatments must fit ONE page"), so the fixtures here are
 * #3522's own — each patient has exactly three prescribed treatments on one PT VO — and the page
 * count is asserted alongside the wording.
 *
 * **Mutating**: each run generates three notices, archiving each patient's previous one. That is
 * unavoidable and is the same write `admin_vorabinfo_one_page.spec.ts` makes.
 */

test.describe('#3668 Vorabinformation exemption block wording', () => {
  test.describe.configure({ mode: 'serial' });

  /** Generated once and shared: three renders per run is already the cost of testing this. */
  const letters: Record<string, LetterRead> = {};

  test(
    'deployment: three freshly generated letters carry the new wording, and none of the old',
    { tag: ['@Admin', '@VorabinfoWording', '@Mutating'] },
    async ({ request }) => {
      test.setTimeout(600_000);
      const api = new NoticeWordingPage(request);
      const token = await api.adminToken();

      const status = await (await request.get(`${API_BASE}/status`)).json();
      console.log(`#3668 API /status: ${JSON.stringify(status)} — reports the release, not the commit (#3704)`);

      for (const [key, fixture] of Object.entries(FIXTURES)) {
        letters[key] = await api.generateAndRead(fixture, token);
        const l = letters[key];
        console.log(`#3668 generated ${l.label}: notice ${l.noticeId} at ${l.createdAt}, ${l.pages} page(s)`);
        expect(l.text.length, `${l.label} produced readable text`).toBeGreaterThan(500);
      }

      // The new sentence is the one thing all three letters must share, so it is the cheapest
      // single deployment signal.
      for (const [key, l] of Object.entries(letters)) {
        expect(l.text, `${key}: AC3/AC6's new sentence`).toContain(WORDING.alwaysNeeded);
      }
      console.log("#3668 DEPLOYED: all three variants carry the always-needed sentence.");
    },
  );

  test(
    'AC1/AC2/AC3 the standard letter',
    { tag: ['@Admin', '@VorabinfoWording', '@ReadOnly'] },
    async () => {
      const l = letters.regular;
      expect(l, 'the standard letter was generated by the first test').toBeTruthy();
      console.log(`#3668 standard exemption block: ${NoticeWordingPage.around(l.text, 'Bitte überweisen Sie noch kein Geld')}`);

      // AC1 — only the ending phrase changes. Matched in parts: the separator between them is an
      // EN DASH in the template, where the AC's prose writes a comma.
      expect(
        NoticeWordingPage.containsInOrder(l.text, WORDING.ac1),
        "AC1: the callout ends with 'nach Ende Ihrer Behandlung.'",
      ).toBe(true);

      // AC2 — the question is unchanged, the instruction reworded, and it now ends with a full
      // stop. The address itself is entity-driven, so it is matched as a pattern.
      expect(NoticeWordingPage.containsInOrder(l.text, WORDING.ac2), 'AC2: the reworded instruction').toBe(true);
      expect(l.text, 'AC2: and it names an address').toMatch(/Kopie Ihrer Befreiungskarte an \S+@\S+\.\w+\./);

      // AC3 — the new sentence, IMMEDIATELY after AC2's line. Adjacency is the AC's own word, so
      // position is asserted rather than mere presence.
      const ac2End = l.text.indexOf(WORDING.ac2[1]);
      const ac3At = l.text.indexOf(WORDING.alwaysNeeded);
      console.log(`#3668 AC3 adjacency: instruction at ${ac2End}, new sentence at ${ac3At}`);
      expect(ac3At, 'AC3: the new sentence is present').toBeGreaterThan(-1);
      expect(ac3At, 'AC3: and it follows AC2s line').toBeGreaterThan(ac2End);
      const between = l.text.slice(ac2End, ac3At);
      expect(
        between.replace(/[^.]/g, '').length,
        'AC3: immediately after — exactly one sentence end between them',
      ).toBeLessThanOrEqual(2);

      // The superseded wording is gone from the block this ticket owns.
      expect(l.text, "AC2: the old instruction is gone").not.toContain(SUPERSEDED.ac2);
    },
  );

  test(
    'AC4/AC5/AC6 both Blanko variants, with AC6 in its stated position',
    { tag: ['@Admin', '@VorabinfoWording', '@ReadOnly'] },
    async () => {
      for (const key of ['blankoPhysio', 'blankoErgo'] as const) {
        const l = letters[key];
        expect(l, `${key} was generated`).toBeTruthy();
        console.log(`#3668 ${key} exemption block: ${NoticeWordingPage.around(l.text, WORDING.ac5Before, 120, 380)}`);

        // AC4 — only the ending phrase changes; the semicolon clause after it is unchanged.
        expect(l.text, `${key} AC4: the final-invoice sentence`).toContain(WORDING.ac4);

        // AC5 — reworded instruction, with its two unchanged neighbours still around it.
        expect(
          NoticeWordingPage.containsInOrder(l.text, [WORDING.ac5Before, WORDING.ac5]),
          `${key} AC5: 'Dann zahlen Sie nichts.' still precedes the instruction`,
        ).toBe(true);
        expect(l.text, `${key} AC5: the old wording is gone`).not.toContain(SUPERSEDED.befreiungsausweis);

        // AC6 — the new sentence sits BETWEEN the instruction and the health-insurer sentence.
        // That ordering is the whole of AC6, so all three are asserted in sequence.
        expect(
          NoticeWordingPage.containsInOrder(l.text, [
            WORDING.ac5Before,
            WORDING.ac5,
            WORDING.alwaysNeeded,
            WORDING.ac5After,
          ]),
          `${key} AC6: new sentence after the instruction and before 'Eine Zuzahlungsbefreiung können Sie…'`,
        ).toBe(true);

        // AC4's old ending must not survive anywhere in the Blanko letter — unlike the standard
        // one, where a second copy of the sentence legitimately still carries it (see the FINDING).
        expect(l.text, `${key}: no 'nach Behandlungsende' left`).not.toContain(SUPERSEDED.behandlungsende);
      }
    },
  );

  test(
    'FINDING: the standard letter still says "nach Behandlungsende" a few lines below the corrected callout',
    { tag: ['@Admin', '@VorabinfoWording', '@ReadOnly'] },
    async () => {
      const l = letters.regular;
      expect(l, 'the standard letter was generated').toBeTruthy();

      const updated = l.text.indexOf('nach Ende Ihrer Behandlung');
      const stale = l.text.indexOf(SUPERSEDED.behandlungsende);
      console.log(`#3668 standard letter: 'Ende Ihrer Behandlung' at ${updated}, 'Behandlungsende' at ${stale}`);
      console.log(`#3668 stale sentence in context: ${NoticeWordingPage.around(l.text, SUPERSEDED.behandlungsende, 160, 180)}`);

      expect(updated, "AC1's corrected callout is there").toBeGreaterThan(-1);

      if (stale > -1) {
        console.log(
          '#3668 FINDING (for the PM): the standard Vorabinformation carries its own copy of the sentence AC4 ' +
            'corrects in the Blanko letter — "Sie erhalten die finale Rechnung nach Behandlungsende, berechnet ' +
            'werden dabei nur tatsächlich durchgeführte Behandlungen." — and it was not updated. So one letter now ' +
            'says it both ways a few lines apart ("nach Ende Ihrer Behandlung" in the callout, "nach ' +
            'Behandlungsende" in the body), while the Blanko letter says it only the new way. Strictly out of ' +
            'scope per "does NOT change: any other paragraph of either letter", but it is the ops team\'s own ' +
            'corrected phrase left behind in the letter they corrected — a wording decision, not a defect.',
        );
        expect(stale, 'the stale copy sits AFTER the corrected callout, in the body').toBeGreaterThan(updated);
      } else {
        console.log('#3668: the body sentence has since been aligned too — the finding is closed.');
      }
    },
  );

  test(
    '#3522 regression: the added sentence did not push any variant to a second page',
    { tag: ['@Admin', '@VorabinfoWording', '@ReadOnly'] },
    async () => {
      // The commit's own note: the new sentence runs to a further line on all three variants, and
      // both the regular letter and the Ergotherapie Blanko went to TWO pages until the paragraph
      // gaps were tightened from 5px to 3px. #3522 requires one page for a ≤3-treatment letter, and
      // these fixtures are #3522's own, so this is the regression that tension creates.
      for (const [key, l] of Object.entries(letters)) {
        console.log(`#3668/#3522 ${key}: ${l.pages} page(s)`);
        expect(l.pages, `${key} still fits one page after the added sentence`).toBe(1);
      }
    },
  );

  test(
    'the archive is a timeline: the new wording starts at a cutover and nothing before it was rewritten',
    { tag: ['@Admin', '@VorabinfoWording', '@ReadOnly', '@Slow'] },
    async ({ request }) => {
      test.setTimeout(900_000);
      const api = new NoticeWordingPage(request);
      const token = await api.adminToken();

      // A notice is archived at generation and never re-rendered, so the archive is a per-render
      // timeline of the template — the #3522 technique. What it can show is the CUTOVER, and that
      // nothing before it was rewritten; what it cannot show is whether today's template is right,
      // which is why every AC above runs on a letter this file generated.
      //
      // Two things make the scan awkward and both are handled rather than worked around:
      // the oldest rows' S3 objects are **gone** (a 3-month-old signed file reads as 0 bytes, the
      // same 404 #3524 measured on Infoblätter), so the far end is unusable; and every run pushes
      // its own three renders to the top, so the recent window fills with post-fix letters. The
      // scan therefore walks back from the top, skips this run's own ids and anything unreadable,
      // and stops at the first OLD-wording letter — which is the boundary it is looking for.
      const mine = new Set(Object.values(letters).map((l) => l.noticeId));
      const recent = await api.recentNotices(token, 60);

      let newest: { id: number; createdAt: string } | null = null;
      let oldest: { id: number; createdAt: string } | null = null;
      let read = 0;
      let unreadable = 0;
      for (const row of recent) {
        if (read >= 25 || oldest) break;
        if (mine.has(row.id) || !row.url) continue;
        const l = await api.readNotice(row, token);
        if (!l.text) {
          unreadable++;
          continue;
        }
        read++;
        const isNew = l.text.includes(WORDING.alwaysNeeded);
        if (isNew) {
          // Keep the OLDEST new-wording row seen so far — the lower edge of the cutover.
          newest = { id: row.id, createdAt: row.createdAt };
        } else {
          oldest = { id: row.id, createdAt: row.createdAt };
        }
      }

      console.log(
        `#3668 archive scan: ${read} readable, ${unreadable} unreadable (their S3 objects are gone); ` +
          `oldest NEW-wording ${JSON.stringify(newest)}; newest OLD-wording ${JSON.stringify(oldest)}`,
      );
      expect(read, 'the scan found readable archived notices').toBeGreaterThan(0);

      if (!oldest) {
        // Legitimate on an archive that has turned over entirely since the deploy: every readable
        // row is post-fix. Reported rather than failed — it is a property of the data, not of the
        // ticket, and the ACs above have already been verified on fresh renders.
        console.log(
          `#3668 archive: no pre-fix letter left within ${read} readable rows — the recent window has turned ` +
            'over. The ACs are verified on the fresh renders above; this test only dates the change.',
        );
        return;
      }

      expect(newest, 'there is a new-wording letter above the boundary').toBeTruthy();
      console.log(
        `#3668 cutover: the last letter without the new sentence is ${oldest.id} (${oldest.createdAt}); ` +
          `the first with it that this scan reached is ${(newest as { id: number }).id} (${(newest as { createdAt: string }).createdAt}).`,
      );
      // The ticket's own statement: existing letters keep their wording. So the boundary is a
      // boundary — a pre-fix letter still reads pre-fix today.
      expect(
        Date.parse((newest as { createdAt: string }).createdAt),
        'AC-wide: the change starts at a point in time and nothing older was rewritten',
      ).toBeGreaterThan(Date.parse(oldest.createdAt));
    },
  );

  test(
    'the extractor gap: pdfText() silently deletes the sentence AC1 is about',
    { tag: ['@Admin', '@VorabinfoWording', '@ReadOnly'] },
    async () => {
      const l = letters.regular;
      expect(l, 'the standard letter was generated').toBeTruthy();

      // Pinned so nobody re-diagnoses this as a rendering defect. `pdfText()` drops the run, so the
      // callout reads "…erhalten Sie erst nach Sie haben eine Zuzahlungsbefreiung?"; `pdfDocText()`
      // has it in full. Same gap #3559's reminder letter hit.
      const naiveHasIt = NoticeWordingPage.containsInOrder(l.naiveText, WORDING.ac1);
      const docHasIt = NoticeWordingPage.containsInOrder(l.text, WORDING.ac1);
      console.log(`#3668 pdfText() sees AC1's sentence: ${naiveHasIt}; pdfDocText(): ${docHasIt}`);
      console.log(`#3668 pdfText() renders it as: ${NoticeWordingPage.around(l.naiveText, 'Bitte überweisen Sie noch kein Geld', 0, 220)}`);

      expect(docHasIt, 'pdfDocText is the extractor to use for this letter').toBe(true);
      if (!naiveHasIt) {
        console.log(
          '#3668 NOTE: a test written on pdfText() would fail AC1 on a correct letter. Use pdfDocText() ' +
            'from pdf-layout.ts for any assertion on the Vorabinformation callout.',
        );
      }
    },
  );
});
