import { Page, expect } from '@playwright/test';
import { AppPage } from '../base/app.page';
import { pdfText } from '../util/pdf-text';

export type PatientAddressHit = {
  id: number;
  patientId: number;
  address: string;
  type: string;
  isBilling: boolean;
};

export type Notice = {
  id: number;
  status: string;
  createdAt: string;
  signedFileUrl: string;
  originalFileName: string;
};

/**
 * Letters that print a patient's postal address (RC 3.11, #3370).
 *
 * Surface notes, all verified live on staging:
 *  - The Vorabinformation lives on the patient form (`/patient-management/{id}/edit`) under the
 *    VORABINFORMATION section, and is (re)generated by
 *    `POST /patients/{id}/generate-pre-treatment-notice/{discipline}` with `{"variant":"regular"|"blanko"}`.
 *    The existing notice is archived and a new one created — which is exactly what the fix needs,
 *    because **a stored PDF keeps whatever text it was rendered with**. The corrected address only
 *    shows up on a letter generated after the fix was deployed; re-reading an old file proves
 *    nothing. (The PR carries the same note as a deploy step for the #3332 invoice-PDF backfill.)
 *  - Generated letters are listed at `GET /pre_treatment_notices?patient=/patients/{id}` and each
 *    carries a short-lived pre-signed S3 `signedFileUrl`. That URL must be fetched from inside the
 *    page context — see `fetchPdf`.
 *  - `PatientAddress` is not an ApiResource of its own; addresses are only serialized on the patients
 *    collection/item, so finding fixtures means scanning that collection.
 */
export class LettersPage extends AppPage {
  /** German country marker sitting immediately before a postal code — the case #3370 fixes. */
  static readonly MARKER_BEFORE_PLZ = /(^|[\s,])D[\s,]+\d{5}\b/;

  /** German country marker at the very end of the address — the case #2503 already handled. */
  static readonly MARKER_TRAILING = /[,\s]D\s*$/;

  constructor(page: Page) {
    super(page);
  }

  /** Signs the request with the bearer token the app keeps in `auth-state`. */
  private async apiJson(path: string, init?: { method?: string; body?: any }): Promise<{ status: number; json: any }> {
    return await this.page.evaluate(
      async ([p, method, body]: [string, string, string | null]) => {
        let token: string | null = null;
        try {
          const j = JSON.parse(localStorage.getItem('auth-state') || '');
          token = j.token || j.accessToken || j.access_token || null;
        } catch {
          /* the caller asserts on the status it gets */
        }
        const r = await fetch(`https://api.staging.therapios.de${p}`, {
          method,
          headers: {
            ...(token ? { Authorization: `Bearer ${token}` } : {}),
            Accept: 'application/ld+json',
            ...(body ? { 'Content-Type': 'application/ld+json' } : {}),
          },
          ...(body ? { body } : {}),
        });
        const text = await r.text();
        try {
          return { status: r.status, json: JSON.parse(text) };
        } catch {
          return { status: r.status, json: { raw: text.slice(0, 500) } };
        }
      },
      [path, init?.method ?? 'GET', init?.body ? JSON.stringify(init.body) : null] as [string, string, string | null],
    );
  }

  /** A patient's addresses. Only the item endpoint serializes them for a single patient. */
  async addresses(patientId: number): Promise<any[]> {
    const res = await this.apiJson(`/patients/${patientId}`);
    expect(res.status, `GET /patients/${patientId}`).toBe(200);
    return res.json.patientAddresses ?? [];
  }

  /**
   * Scans the patients collection for addresses carrying a country marker.
   *
   * `pages` is bounded on purpose: the collection is ~8.4k patients over 84 pages and a full sweep
   * takes minutes. The trailing-marker form is on the great majority of imported addresses, so a
   * handful of pages is enough to find fixtures for it; the before-postal-code form is much rarer.
   */
  async findMarkedAddresses(pages = 12, perPage = 100): Promise<{ beforePlz: PatientAddressHit[]; trailing: PatientAddressHit[]; scanned: number }> {
    return await this.page.evaluate(
      async ([pageCount, itemsPerPage]: [number, number]) => {
        let token: string | null = null;
        try {
          const j = JSON.parse(localStorage.getItem('auth-state') || '');
          token = j.token || j.accessToken || j.access_token || null;
        } catch {
          /* an unauthenticated scan simply returns nothing */
        }
        const beforePlz: any[] = [];
        const trailing: any[] = [];
        let scanned = 0;
        for (let p = 1; p <= pageCount; p++) {
          const r = await fetch(`https://api.staging.therapios.de/patients?page=${p}&itemsPerPage=${itemsPerPage}`, {
            headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}), Accept: 'application/ld+json' },
          });
          if (!r.ok) break;
          const j = await r.json();
          const members = j.member ?? j['hydra:member'] ?? [];
          if (!members.length) break;
          scanned += members.length;
          for (const m of members) {
            for (const a of m.patientAddresses ?? []) {
              const text = (a.address || '').trim();
              const hit = { id: m.id, patientId: m.patientId, address: text, type: a.type, isBilling: !!a.isBilling };
              if (/(^|[\s,])D[\s,]+\d{5}\b/.test(text)) beforePlz.push(hit);
              else if (/[,\s]D\s*$/.test(text)) trailing.push(hit);
            }
          }
        }
        return { beforePlz, trailing, scanned };
      },
      [pages, perPage] as [number, number],
    );
  }

  // ───────────────────────────── Vorabinformation ────────────────────────────

  async notices(patientId: number): Promise<Notice[]> {
    const res = await this.apiJson(
      `/pre_treatment_notices?page=1&itemsPerPage=100&order%5BcreatedAt%5D=desc&patient=%2Fpatients%2F${patientId}`,
    );
    expect(res.status, 'GET /pre_treatment_notices').toBe(200);
    return res.json.member ?? res.json['hydra:member'] ?? [];
  }

  /**
   * Generates a fresh Vorabinformation and returns it.
   *
   * This is a write: the patient's current notice is archived and a new one created. It is the only
   * way to observe the rendering fix — see the class docs on why re-reading a stored PDF cannot.
   */
  async generateNotice(
    patientId: number,
    discipline: 'physiotherapy' | 'ergotherapy' | 'speech_therapy' = 'physiotherapy',
    variant: 'regular' | 'blanko' = 'regular',
  ): Promise<{ status: number; notice: any }> {
    const res = await this.apiJson(`/patients/${patientId}/generate-pre-treatment-notice/${discipline}`, {
      method: 'POST',
      body: { variant },
    });
    return { status: res.status, notice: res.json };
  }

  /** Downloads a pre-signed S3 letter URL from inside the page. `null` when the object is gone. */
  async fetchPdf(url: string): Promise<{ status: number; buffer: Buffer | null }> {
    const res = await this.page.evaluate(async (u: string) => {
      const r = await fetch(u);
      return { status: r.status, bytes: r.ok ? Array.from(new Uint8Array(await r.arrayBuffer())) : [] };
    }, url);
    return { status: res.status, buffer: res.status === 200 ? Buffer.from(res.bytes) : null };
  }

  /** The readable text of a letter, one line per text block. */
  async letterText(url: string): Promise<string> {
    const res = await this.fetchPdf(url);
    expect(res.status, 'downloading the generated letter').toBe(200);
    return pdfText(res.buffer!);
  }

  /**
   * Like `letterText`, but `null` when the stored file is no longer downloadable.
   *
   * Older archived letters on staging do 404 on their S3 object — the record outlives the file — so
   * a scan over the archive must tolerate that rather than fail on it.
   */
  async tryLetterText(url: string): Promise<string | null> {
    const res = await this.fetchPdf(url);
    return res.buffer ? pdfText(res.buffer) : null;
  }

  /**
   * The recipient block of a letter: the lines between the sender strip and the dateline.
   *
   * The address is printed as its own lines here, which is what makes the #3370 assertion precise —
   * the bug puts the marker on the STREET line ("Ernst-Thälmann-Str. 29, D"), so asserting on the
   * whole document would also match the marker in unrelated body text.
   */
  static recipientBlock(text: string): string[] {
    const lines = text.split('\n').map((l) => l.trim()).filter(Boolean);
    // the dateline ("Teltow, 17.08.2026") closes the recipient block
    const end = lines.findIndex((l) => /^[A-Za-zÄÖÜäöüß .-]+,\s*\d{2}\.\d{2}\.\d{4}$/.test(l));
    // line 0 is the sender strip printed above the address window
    return lines.slice(1, end > 1 ? end : 6);
  }
}
